# Generated by Django 2.2.4 on 2020-11-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_auto_20190204_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(blank=True, choices=[('ALLY', 'Ally'), ('VENMO', 'Venmo'), ('CHASE', 'Chase'), ('AMAZON', 'Amazon')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
