# Generated by Django 2.2.4 on 2020-11-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0011_auto_20201101_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Altname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type': '2'}, on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
            ],
        ),
    ]
