# Generated by Django 2.2.4 on 2020-11-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0012_account_altname_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='buffet',
            field=models.IntegerField(blank=True, choices=[(1, 'Need'), (2, 'Want'), (3, 'Income'), (4, 'Ignore')], null=True),
        ),
    ]
