# Generated by Django 2.2.4 on 2020-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0014_auto_20201102_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='buffet',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Need'), (2, 'Want'), (3, 'Income'), (4, 'Ignore')], null=True),
        ),
        migrations.AlterField(
            model_name='split',
            name='buffet',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Need'), (2, 'Want'), (3, 'Income'), (4, 'Ignore')], null=True),
        ),
    ]
